plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jsaq.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.jsaq.app"
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName "1.2"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
